/**
 * Narrow boundary for the "remind me to send the response to my local
 * chapter" checkbox.
 *
 * There is no confirmed live reminder queue table, scheduled worker, or
 * application email sender yet. This module intentionally does not call
 * Supabase or any network endpoint — it validates its input shape and
 * always reports the reminder feature as unavailable, so the UI can never
 * claim a reminder was scheduled when nothing will actually send one.
 *
 * Proposed reminder queue contract (not applied to live Supabase by this
 * change — this is a design proposal for a future migration):
 *
 *   create table public.chapter_response_reminders (
 *     id bigint generated by default as identity primary key,
 *     county_id bigint not null references public.counties(id),
 *     goal_id bigint not null references public.county_records_request_goals(id),
 *     request_profile_id uuid not null references public.request_profiles(id),
 *     contact_email text not null,           -- normalized, lower(trim(email))
 *     consented_at timestamptz not null,
 *     status text not null default 'pending', -- pending | sent | cancelled
 *     created_at timestamptz not null default now()
 *   );
 *
 * A contact may prepare multiple requests, so this is a queue of consent
 * events keyed by (contact_email, county_id, goal_id) — never a single
 * boolean or goal column bolted onto county_contacts. Sending still needs a
 * scheduled worker (reminder timing is not decided here — do not invent
 * one) and an email provider, plus an unsubscribe/cancellation path, none
 * of which exist yet.
 */

export const REMINDER_BACKEND_AVAILABLE = false;

function isNonEmptyString(value) {
  return typeof value === "string" && value.trim().length > 0;
}

/**
 * Validates a reminder request's shape and truthfully reports that no
 * backend exists to schedule it. Never performs a network call and never
 * claims `scheduled: true`.
 */
export function requestChapterReminder({ email, countyId, goalId, requestProfileId, consentedAt }) {
  if (!isNonEmptyString(email) || !countyId || !goalId || !isNonEmptyString(requestProfileId) || !isNonEmptyString(consentedAt)) {
    return { scheduled: false, reason: "invalid_request" };
  }

  if (!REMINDER_BACKEND_AVAILABLE) {
    return { scheduled: false, reason: "backend_unavailable" };
  }

  // Unreachable until a real backend exists; left explicit rather than
  // removed so the truthful branch above is the only path that runs today.
  return { scheduled: false, reason: "backend_unavailable" };
}
