-- Flock Block Tennessee
-- Rich post content, flexible media, admin upload permissions, and
-- meeting-listing visibility support.
--
-- Target: the confirmed public.posts schema as of 2026-08-03.
-- Safe to rerun. This migration does not recreate, reattach, or change
-- ownership of any identity sequence.

begin;

-- ---------------------------------------------------------------------------
-- 0. Confirm required existing objects
-- ---------------------------------------------------------------------------

do $$
begin
  if to_regclass('public.posts') is null then
    raise exception 'public.posts does not exist';
  end if;

  if to_regclass('public.portal_accounts') is null then
    raise exception 'public.portal_accounts does not exist';
  end if;

  if not exists (select 1 from storage.buckets where id = 'filebucket') then
    raise exception 'The Storage bucket filebucket does not exist';
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 1. Extend posts for structured rich text and feed-only visibility
-- ---------------------------------------------------------------------------

alter table public.posts
  add column if not exists body_rich jsonb,
  add column if not exists show_in_status_feed boolean;

update public.posts
set show_in_status_feed = true
where show_in_status_feed is null;

alter table public.posts
  alter column show_in_status_feed set default true,
  alter column show_in_status_feed set not null;

alter table public.posts
  drop constraint if exists posts_body_rich_root_check;

alter table public.posts
  add constraint posts_body_rich_root_check
  check (
    body_rich is null
    or (
      jsonb_typeof(body_rich) = 'object'
      and body_rich ->> 'type' = 'doc'
    )
  );

create index if not exists posts_meeting_list_idx
  on public.posts(event_start asc)
  where content_type = 'meeting'
    and event_start is not null;

create index if not exists posts_public_status_feed_visibility_idx
  on public.posts(status, show_in_status_feed, scope, approved_at desc);

-- ---------------------------------------------------------------------------
-- 2. Flexible ordered media records
-- ---------------------------------------------------------------------------

create table if not exists public.post_media (
  id bigint generated by default as identity primary key,
  post_id bigint not null,
  media_type text not null,
  position integer not null default 0,
  is_primary boolean not null default false,
  storage_path text,
  external_url text,
  provider text,
  provider_media_id text,
  component_key text,
  configuration jsonb,
  alt_text text,
  caption text,
  credit text,
  source_url text,
  created_by uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint post_media_post_id_fkey
    foreign key (post_id)
    references public.posts(id)
    on update cascade
    on delete cascade,
  constraint post_media_created_by_fkey
    foreign key (created_by)
    references auth.users(id)
    on delete restrict
);

alter table public.post_media
  drop constraint if exists post_media_type_check;

alter table public.post_media
  add constraint post_media_type_check
  check (media_type in ('image', 'external_video', 'component', 'external_link'));

alter table public.post_media
  drop constraint if exists post_media_position_check;

alter table public.post_media
  add constraint post_media_position_check
  check (position >= 0);

alter table public.post_media
  drop constraint if exists post_media_required_fields_check;

alter table public.post_media
  add constraint post_media_required_fields_check
  check (
    (
      media_type = 'image'
      and nullif(trim(storage_path), '') is not null
      and storage_path like 'status/%'
      and nullif(trim(alt_text), '') is not null
    )
    or
    (
      media_type = 'external_video'
      and nullif(trim(external_url), '') is not null
      and external_url ~* '^https://'
      and nullif(trim(provider), '') is not null
      and nullif(trim(provider_media_id), '') is not null
    )
    or
    (
      media_type = 'component'
      and nullif(trim(component_key), '') is not null
    )
    or
    (
      media_type = 'external_link'
      and nullif(trim(external_url), '') is not null
      and external_url ~* '^https://'
    )
  );

alter table public.post_media
  drop constraint if exists post_media_source_url_check;

alter table public.post_media
  add constraint post_media_source_url_check
  check (
    source_url is null
    or (
      nullif(trim(source_url), '') is not null
      and source_url ~* '^https://'
    )
  );

create index if not exists post_media_post_position_idx
  on public.post_media(post_id, position, id);

create unique index if not exists post_media_one_primary_per_post_idx
  on public.post_media(post_id)
  where is_primary;

-- ---------------------------------------------------------------------------
-- 3. Media timestamps and the hard six-image limit
-- ---------------------------------------------------------------------------

create or replace function public.set_post_media_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists post_media_set_updated_at on public.post_media;
create trigger post_media_set_updated_at
before update on public.post_media
for each row execute function public.set_post_media_updated_at();

create or replace function public.enforce_post_media_image_limit()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  existing_image_count integer;
begin
  if new.media_type <> 'image' then
    return new;
  end if;

  -- Serialize image-count changes for the same post so concurrent inserts
  -- cannot independently pass the six-image check.
  perform pg_advisory_xact_lock(
    hashtextextended('post-media-image-limit:' || new.post_id::text, 0)
  );

  select count(*)
  into existing_image_count
  from public.post_media as media
  where media.post_id = new.post_id
    and media.media_type = 'image'
    and media.id is distinct from new.id;

  if existing_image_count >= 6 then
    raise exception 'A post may contain no more than six uploaded images';
  end if;

  return new;
end;
$$;

drop trigger if exists post_media_enforce_image_limit on public.post_media;
create trigger post_media_enforce_image_limit
before insert or update of post_id, media_type on public.post_media
for each row execute function public.enforce_post_media_image_limit();

-- ---------------------------------------------------------------------------
-- 4. Grants and row-level security
-- ---------------------------------------------------------------------------

grant select on public.post_media to anon;
grant select, insert, update, delete on public.post_media to authenticated;

-- Grant access to the identity sequence linked to post_media.id without
-- attempting to alter its ownership.
do $$
declare
  media_sequence_name text;
begin
  media_sequence_name := pg_get_serial_sequence('public.post_media', 'id');

  if media_sequence_name is null then
    raise exception 'public.post_media.id has no attached identity sequence';
  end if;

  execute format(
    'grant usage, select on sequence %s to authenticated',
    media_sequence_name::regclass
  );
end
$$;

alter table public.post_media enable row level security;

drop policy if exists "Public can read approved post media" on public.post_media;
create policy "Public can read approved post media"
on public.post_media
for select
to public
using (
  exists (
    select 1
    from public.posts as post
    where post.id = post_media.post_id
      and post.status = 'approved'
      and post.show_in_status_feed = true
  )
);

drop policy if exists "Admins can read all post media" on public.post_media;
create policy "Admins can read all post media"
on public.post_media
for select
to authenticated
using (
  exists (
    select 1
    from public.portal_accounts as account
    where account.user_id = auth.uid()
      and account.role = 'admin'
      and account.status = 'active'
  )
);

drop policy if exists "Admins can insert post media" on public.post_media;
create policy "Admins can insert post media"
on public.post_media
for insert
to authenticated
with check (
  created_by = auth.uid()
  and exists (
    select 1
    from public.portal_accounts as account
    where account.user_id = auth.uid()
      and account.role = 'admin'
      and account.status = 'active'
  )
);

drop policy if exists "Admins can update post media" on public.post_media;
create policy "Admins can update post media"
on public.post_media
for update
to authenticated
using (
  exists (
    select 1
    from public.portal_accounts as account
    where account.user_id = auth.uid()
      and account.role = 'admin'
      and account.status = 'active'
  )
)
with check (
  exists (
    select 1
    from public.portal_accounts as account
    where account.user_id = auth.uid()
      and account.role = 'admin'
      and account.status = 'active'
  )
);

drop policy if exists "Admins can delete post media" on public.post_media;
create policy "Admins can delete post media"
on public.post_media
for delete
to authenticated
using (
  exists (
    select 1
    from public.portal_accounts as account
    where account.user_id = auth.uid()
      and account.role = 'admin'
      and account.status = 'active'
  )
);

-- ---------------------------------------------------------------------------
-- 5. Configure filebucket and administrator upload permissions
-- ---------------------------------------------------------------------------

update storage.buckets
set
  public = true,
  file_size_limit = 500000,
  allowed_mime_types = array[
    'image/jpeg',
    'image/png',
    'image/webp'
  ]::text[]
where id = 'filebucket';

-- The existing public-read policy remains unchanged so the seeded image paths
-- continue to work. These policies add admin-only writes under status/**.

drop policy if exists "Admins can upload status media" on storage.objects;
create policy "Admins can upload status media"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'filebucket'
  and (storage.foldername(name))[1] = 'status'
  and exists (
    select 1
    from public.portal_accounts as account
    where account.user_id = auth.uid()
      and account.role = 'admin'
      and account.status = 'active'
  )
);

drop policy if exists "Admins can update status media" on storage.objects;
create policy "Admins can update status media"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'filebucket'
  and (storage.foldername(name))[1] = 'status'
  and exists (
    select 1
    from public.portal_accounts as account
    where account.user_id = auth.uid()
      and account.role = 'admin'
      and account.status = 'active'
  )
)
with check (
  bucket_id = 'filebucket'
  and (storage.foldername(name))[1] = 'status'
  and exists (
    select 1
    from public.portal_accounts as account
    where account.user_id = auth.uid()
      and account.role = 'admin'
      and account.status = 'active'
  )
);

drop policy if exists "Admins can delete status media" on storage.objects;
create policy "Admins can delete status media"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'filebucket'
  and (storage.foldername(name))[1] = 'status'
  and exists (
    select 1
    from public.portal_accounts as account
    where account.user_id = auth.uid()
      and account.role = 'admin'
      and account.status = 'active'
  )
);

commit;

-- ---------------------------------------------------------------------------
-- 6. Single-result verification
-- ---------------------------------------------------------------------------

select
  exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'posts'
      and column_name = 'body_rich'
  ) as posts_has_body_rich,
  exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'posts'
      and column_name = 'show_in_status_feed'
  ) as posts_has_feed_visibility,
  to_regclass('public.post_media') is not null as post_media_exists,
  (select count(*) from public.posts where show_in_status_feed) as feed_visible_post_count,
  (select file_size_limit from storage.buckets where id = 'filebucket') as image_limit_bytes,
  (select allowed_mime_types from storage.buckets where id = 'filebucket') as allowed_image_types;