begin;

-- Chapter masters may read media attached to their own county posts so the
-- composer can hydrate existing drafts without exposing another county's work.
drop policy if exists "Chapter masters can read own post media" on public.post_media;
create policy "Chapter masters can read own post media"
on public.post_media
for select
to authenticated
using (
  exists (
    select 1
    from public.posts as post
    join public.portal_accounts as account
      on account.user_id = (select auth.uid())
     and account.role = 'chapter_master'
     and account.status = 'active'
     and account.county_id = post.county_id
    where post.id = post_media.post_id
      and post.author_user_id = (select auth.uid())
      and post.scope = 'county'
  )
);

drop policy if exists "Chapter masters can insert own post media" on public.post_media;
create policy "Chapter masters can insert own post media"
on public.post_media
for insert
to authenticated
with check (
  created_by = (select auth.uid())
  and exists (
    select 1
    from public.posts as post
    join public.portal_accounts as account
      on account.user_id = (select auth.uid())
     and account.role = 'chapter_master'
     and account.status = 'active'
     and account.county_id = post.county_id
    where post.id = post_media.post_id
      and post.author_user_id = (select auth.uid())
      and post.scope = 'county'
      and post.status in ('draft', 'rejected')
  )
);

drop policy if exists "Chapter masters can update own post media" on public.post_media;
create policy "Chapter masters can update own post media"
on public.post_media
for update
to authenticated
using (
  created_by = (select auth.uid())
  and exists (
    select 1
    from public.posts as post
    join public.portal_accounts as account
      on account.user_id = (select auth.uid())
     and account.role = 'chapter_master'
     and account.status = 'active'
     and account.county_id = post.county_id
    where post.id = post_media.post_id
      and post.author_user_id = (select auth.uid())
      and post.scope = 'county'
      and post.status in ('draft', 'rejected')
  )
)
with check (
  created_by = (select auth.uid())
  and exists (
    select 1
    from public.posts as post
    join public.portal_accounts as account
      on account.user_id = (select auth.uid())
     and account.role = 'chapter_master'
     and account.status = 'active'
     and account.county_id = post.county_id
    where post.id = post_media.post_id
      and post.author_user_id = (select auth.uid())
      and post.scope = 'county'
      and post.status in ('draft', 'rejected')
  )
);

drop policy if exists "Chapter masters can delete own post media" on public.post_media;
create policy "Chapter masters can delete own post media"
on public.post_media
for delete
to authenticated
using (
  created_by = (select auth.uid())
  and exists (
    select 1
    from public.posts as post
    join public.portal_accounts as account
      on account.user_id = (select auth.uid())
     and account.role = 'chapter_master'
     and account.status = 'active'
     and account.county_id = post.county_id
    where post.id = post_media.post_id
      and post.author_user_id = (select auth.uid())
      and post.scope = 'county'
      and post.status in ('draft', 'rejected')
  )
);

-- Storage paths are generated by the client as:
-- status/<county-slug>/<post-id>/<uuid>.webp
-- Bind every path component to the caller's active account and owned post.
drop policy if exists "Chapter masters can upload own status media" on storage.objects;
create policy "Chapter masters can upload own status media"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'filebucket'
  and name ~ '^status/[a-z0-9]+(?:-[a-z0-9]+)*/[0-9]+/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.webp$'
  and exists (
    select 1
    from public.posts as post
    join public.counties as county on county.id = post.county_id
    join public.portal_accounts as account
      on account.user_id = (select auth.uid())
     and account.role = 'chapter_master'
     and account.status = 'active'
     and account.county_id = post.county_id
    where post.id::text = (storage.foldername(storage.objects.name))[3]
      and county.slug = (storage.foldername(storage.objects.name))[2]
      and post.author_user_id = (select auth.uid())
      and post.scope = 'county'
      and post.status in ('draft', 'rejected')
  )
);

drop policy if exists "Chapter masters can update own status media" on storage.objects;
create policy "Chapter masters can update own status media"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'filebucket'
  and name ~ '^status/[a-z0-9]+(?:-[a-z0-9]+)*/[0-9]+/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.webp$'
  and exists (
    select 1
    from public.posts as post
    join public.counties as county on county.id = post.county_id
    join public.portal_accounts as account
      on account.user_id = (select auth.uid())
     and account.role = 'chapter_master'
     and account.status = 'active'
     and account.county_id = post.county_id
    where post.id::text = (storage.foldername(storage.objects.name))[3]
      and county.slug = (storage.foldername(storage.objects.name))[2]
      and post.author_user_id = (select auth.uid())
      and post.scope = 'county'
      and post.status in ('draft', 'rejected')
  )
)
with check (
  bucket_id = 'filebucket'
  and name ~ '^status/[a-z0-9]+(?:-[a-z0-9]+)*/[0-9]+/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.webp$'
  and exists (
    select 1
    from public.posts as post
    join public.counties as county on county.id = post.county_id
    join public.portal_accounts as account
      on account.user_id = (select auth.uid())
     and account.role = 'chapter_master'
     and account.status = 'active'
     and account.county_id = post.county_id
    where post.id::text = (storage.foldername(storage.objects.name))[3]
      and county.slug = (storage.foldername(storage.objects.name))[2]
      and post.author_user_id = (select auth.uid())
      and post.scope = 'county'
      and post.status in ('draft', 'rejected')
  )
);

drop policy if exists "Chapter masters can delete own status media" on storage.objects;
create policy "Chapter masters can delete own status media"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'filebucket'
  and name ~ '^status/[a-z0-9]+(?:-[a-z0-9]+)*/[0-9]+/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.webp$'
  and exists (
    select 1
    from public.posts as post
    join public.counties as county on county.id = post.county_id
    join public.portal_accounts as account
      on account.user_id = (select auth.uid())
     and account.role = 'chapter_master'
     and account.status = 'active'
     and account.county_id = post.county_id
    where post.id::text = (storage.foldername(storage.objects.name))[3]
      and county.slug = (storage.foldername(storage.objects.name))[2]
      and post.author_user_id = (select auth.uid())
      and post.scope = 'county'
      and post.status in ('draft', 'rejected')
  )
);

commit;
