-- Email campaigns, one-time records-request reminders, delivery tracking, and
-- unsubscribe/suppression controls. Sending is performed by Edge Functions;
-- recipient addresses are never exposed through direct table access.

do $$
begin
  if to_regclass('public.security_audit_events') is null then
    raise exception 'security_audit_events must exist before applying the email migration';
  end if;

  perform actor_user_id, county_id, event_type, target_table, target_id, event_data
  from public.security_audit_events
  where false;
end
$$;

alter table public.county_contacts
  add column if not exists subscription_status text not null default 'active',
  add column if not exists unsubscribed_at timestamptz,
  add column if not exists unsubscribe_token uuid not null default extensions.gen_random_uuid();

alter table public.county_contacts
  drop constraint if exists county_contacts_subscription_status_check;

alter table public.county_contacts
  add constraint county_contacts_subscription_status_check
  check (subscription_status in ('active', 'unsubscribed'));

create unique index if not exists county_contacts_unsubscribe_token_key
  on public.county_contacts (unsubscribe_token);

create table public.email_suppressions (
  email text primary key,
  reason text not null check (reason in ('unsubscribe', 'bounce', 'complaint', 'admin')),
  source_event_id text,
  suppressed_at timestamptz not null default now(),
  check (email = lower(btrim(email)) and char_length(email) between 3 and 320)
);

create table public.email_campaigns (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete restrict,
  requested_by uuid not null references auth.users(id) on delete restrict,
  requested_at timestamptz not null default now(),
  target_scope text not null check (target_scope in ('global', 'county')),
  county_id bigint references public.counties(id) on delete restrict,
  status text not null default 'requested'
    check (status in ('requested', 'approved', 'sending', 'sent', 'rejected', 'cancelled', 'failed')),
  subject text not null check (char_length(btrim(subject)) between 1 and 180),
  post_snapshot jsonb,
  approved_by uuid references auth.users(id) on delete restrict,
  approved_at timestamptz,
  review_note text check (review_note is null or char_length(review_note) <= 2000),
  send_started_at timestamptz,
  completed_at timestamptz,
  recipient_count integer not null default 0 check (recipient_count >= 0),
  sent_count integer not null default 0 check (sent_count >= 0),
  delivered_count integer not null default 0 check (delivered_count >= 0),
  bounced_count integer not null default 0 check (bounced_count >= 0),
  complained_count integer not null default 0 check (complained_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (target_scope = 'global' and county_id is null)
    or (target_scope = 'county' and county_id is not null)
  ),
  check (
    (status = 'requested' and approved_by is null and approved_at is null and post_snapshot is null)
    or status in ('rejected', 'cancelled')
    or (approved_by is not null and approved_at is not null and jsonb_typeof(post_snapshot) = 'object')
  )
);

create unique index email_campaigns_one_active_request_per_post
  on public.email_campaigns (post_id)
  where status in ('requested', 'approved', 'sending');

create index email_campaigns_status_requested_at_idx
  on public.email_campaigns (status, requested_at desc);

create table public.email_deliveries (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.email_campaigns(id) on delete cascade,
  county_id bigint not null references public.counties(id) on delete restrict,
  recipient_email text not null,
  unsubscribe_token uuid not null default extensions.gen_random_uuid(),
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'sent', 'delivered', 'bounced', 'complained', 'failed', 'suppressed')),
  provider_email_id text unique,
  attempt_count integer not null default 0 check (attempt_count between 0 and 10),
  queued_at timestamptz not null default now(),
  claimed_at timestamptz,
  sent_at timestamptz,
  delivered_at timestamptz,
  failed_at timestamptz,
  last_error_code text check (last_error_code is null or char_length(last_error_code) <= 80),
  unique (campaign_id, recipient_email),
  unique (unsubscribe_token),
  check (recipient_email = lower(btrim(recipient_email)) and char_length(recipient_email) between 3 and 320)
);

create index email_deliveries_worker_idx
  on public.email_deliveries (status, queued_at)
  where status in ('pending', 'processing');

create table public.request_followup_reminders (
  id bigint generated by default as identity primary key,
  email text not null,
  county_id bigint not null references public.counties(id) on delete restrict,
  goal_id bigint not null references public.county_records_request_goals(id) on delete cascade,
  request_profile_id uuid not null references public.request_profiles(id) on delete restrict,
  manage_token uuid not null default extensions.gen_random_uuid(),
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'sent', 'cancelled', 'failed', 'suppressed')),
  consented_at timestamptz not null default now(),
  due_at timestamptz not null default (now() + interval '7 days'),
  provider_email_id text unique,
  attempt_count integer not null default 0 check (attempt_count between 0 and 10),
  claimed_at timestamptz,
  sent_at timestamptz,
  failed_at timestamptz,
  last_error_code text check (last_error_code is null or char_length(last_error_code) <= 80),
  unique (manage_token),
  check (email = lower(btrim(email)) and char_length(email) between 3 and 320),
  check (due_at >= consented_at + interval '6 days 23 hours')
);

create unique index request_followup_reminders_one_open_per_goal_email
  on public.request_followup_reminders (goal_id, email)
  where status in ('pending', 'processing');

create index request_followup_reminders_worker_idx
  on public.request_followup_reminders (status, due_at)
  where status in ('pending', 'processing');

create table public.email_webhook_events (
  event_id text primary key,
  event_type text not null,
  provider_email_id text,
  received_at timestamptz not null default now(),
  processed_at timestamptz not null default now(),
  check (char_length(event_id) between 1 and 200),
  check (char_length(event_type) between 1 and 100)
);

alter table public.email_suppressions enable row level security;
alter table public.email_campaigns enable row level security;
alter table public.email_deliveries enable row level security;
alter table public.request_followup_reminders enable row level security;
alter table public.email_webhook_events enable row level security;

revoke all on table public.email_suppressions from anon, authenticated;
revoke all on table public.email_campaigns from anon, authenticated;
revoke all on table public.email_deliveries from anon, authenticated;
revoke all on table public.request_followup_reminders from anon, authenticated;
revoke all on table public.email_webhook_events from anon, authenticated;

grant select, insert, update, delete on table public.email_suppressions to service_role;
grant select, insert, update, delete on table public.email_campaigns to service_role;
grant select, insert, update, delete on table public.email_deliveries to service_role;
grant select, insert, update, delete on table public.request_followup_reminders to service_role;
grant select, insert, update, delete on table public.email_webhook_events to service_role;

create or replace function public.rrg_subscribe_county_updates(
  p_county_id bigint,
  p_email text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_email text := lower(btrim(p_email));
  v_contact_id bigint;
  v_suppression_reason text;
begin
  if p_county_id is null or not exists (select 1 from public.counties where id = p_county_id) then
    raise exception 'A valid county is required.' using errcode = '22023';
  end if;
  if v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' or char_length(v_email) > 320 then
    raise exception 'Enter a valid email address.' using errcode = '22023';
  end if;

  select reason into v_suppression_reason
  from public.email_suppressions
  where email = v_email;

  if v_suppression_reason in ('bounce', 'complaint', 'admin') then
    return jsonb_build_object('subscribed', false, 'reason', 'suppressed');
  end if;

  delete from public.email_suppressions where email = v_email and reason = 'unsubscribe';

  select id into v_contact_id
  from public.county_contacts
  where county_id = p_county_id and lower(btrim(email)) = v_email
  for update;

  if v_contact_id is null then
    insert into public.county_contacts (county_id, email, subscription_status, unsubscribed_at)
    values (p_county_id, v_email, 'active', null)
    returning id into v_contact_id;
  else
    update public.county_contacts
    set subscription_status = 'active', unsubscribed_at = null
    where id = v_contact_id;
  end if;

  return jsonb_build_object('subscribed', true);
exception
  when unique_violation then
    update public.county_contacts
    set subscription_status = 'active', unsubscribed_at = null
    where county_id = p_county_id and lower(btrim(email)) = v_email;
    return jsonb_build_object('subscribed', true);
end;
$$;

create or replace function public.rrg_request_followup_reminder(
  p_goal_id bigint,
  p_email text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_email text := lower(btrim(p_email));
  v_goal public.county_records_request_goals%rowtype;
  v_profile_status text;
  v_pending_count integer;
  v_reminder_id bigint;
  v_manage_token uuid;
begin
  if v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' or char_length(v_email) > 320 then
    raise exception 'Enter a valid email address.' using errcode = '22023';
  end if;

  select * into v_goal
  from public.county_records_request_goals
  where id = p_goal_id;

  if not found or not v_goal.is_public or v_goal.locked or v_goal.request_profile_id is null then
    raise exception 'This goal is not available for reminders.' using errcode = '42501';
  end if;

  select status into v_profile_status
  from public.request_profiles
  where id = v_goal.request_profile_id;

  if v_profile_status <> 'verified' then
    raise exception 'This request profile is not available for reminders.' using errcode = '42501';
  end if;

  if exists (select 1 from public.email_suppressions where email = v_email) then
    return jsonb_build_object('scheduled', false, 'reason', 'suppressed');
  end if;

  select count(*) into v_pending_count
  from public.request_followup_reminders
  where email = v_email and status in ('pending', 'processing');

  if v_pending_count >= 3 then
    raise exception 'Too many reminders are already scheduled for this address.' using errcode = '54000';
  end if;

  select id, manage_token into v_reminder_id, v_manage_token
  from public.request_followup_reminders
  where goal_id = p_goal_id and email = v_email and status in ('pending', 'processing');

  if v_reminder_id is null then
    insert into public.request_followup_reminders (
      email, county_id, goal_id, request_profile_id, due_at
    ) values (
      v_email, v_goal.county_id, v_goal.id, v_goal.request_profile_id, now() + interval '7 days'
    ) returning id, manage_token into v_reminder_id, v_manage_token;
  end if;

  return jsonb_build_object(
    'scheduled', true,
    'due_at', (select due_at from public.request_followup_reminders where id = v_reminder_id),
    'manage_token', v_manage_token
  );
end;
$$;

create or replace function public.rrg_cancel_followup_reminder(p_manage_token uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.request_followup_reminders
  set status = 'cancelled'
  where manage_token = p_manage_token and status = 'pending';
  return found;
end;
$$;

create or replace function public.rrg_unsubscribe_email(p_token uuid)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_email text;
begin
  select recipient_email into v_email
  from public.email_deliveries
  where unsubscribe_token = p_token;

  if v_email is null then
    return false;
  end if;

  insert into public.email_suppressions (email, reason)
  values (v_email, 'unsubscribe')
  on conflict (email) do update
    set reason = 'unsubscribe', source_event_id = null, suppressed_at = now();

  update public.county_contacts
  set subscription_status = 'unsubscribed', unsubscribed_at = now()
  where lower(btrim(email)) = v_email;

  return true;
end;
$$;

create or replace function public.rrg_request_post_email_campaign(
  p_post_id bigint,
  p_subject text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_account public.portal_accounts%rowtype;
  v_post public.posts%rowtype;
  v_campaign_id bigint;
  v_subject text;
begin
  if v_actor is null then
    raise exception 'Authentication required.' using errcode = '42501';
  end if;

  select * into v_account from public.portal_accounts where user_id = v_actor;
  if not found or v_account.status <> 'active' then
    raise exception 'An active portal account is required.' using errcode = '42501';
  end if;

  select * into v_post from public.posts where id = p_post_id for update;
  if not found then raise exception 'Post not found.' using errcode = 'P0002'; end if;

  if v_account.role = 'chapter_master' and (
    v_post.author_user_id <> v_actor or v_post.scope <> 'county' or v_post.county_id <> v_account.county_id
  ) then
    raise exception 'Chapter masters may email only their own county posts.' using errcode = '42501';
  elsif v_account.role <> 'admin' and v_account.role <> 'chapter_master' then
    raise exception 'Not authorized.' using errcode = '42501';
  end if;

  if v_post.status not in ('draft', 'pending', 'approved') then
    raise exception 'Only draft, pending, or approved posts may be prepared for email.' using errcode = '22023';
  end if;

  v_subject := coalesce(nullif(btrim(p_subject), ''), nullif(btrim(v_post.title), ''));
  if v_subject is null or char_length(v_subject) > 180 then
    raise exception 'Email subject must be between 1 and 180 characters.' using errcode = '22023';
  end if;

  insert into public.email_campaigns (
    post_id, requested_by, target_scope, county_id, subject
  ) values (
    v_post.id, v_actor, v_post.scope, v_post.county_id, v_subject
  ) returning id into v_campaign_id;

  update public.posts set mass_email_requested = true where id = v_post.id;

  insert into public.security_audit_events (
    actor_user_id, county_id, event_type, target_table, target_id, event_data
  ) values (
    v_actor, v_post.county_id, 'email_campaign_requested', 'email_campaigns', v_campaign_id::text,
    jsonb_build_object('post_id', v_post.id, 'scope', v_post.scope)
  );

  return v_campaign_id;
end;
$$;

create or replace function public.rrg_admin_review_email_campaign(
  p_campaign_id bigint,
  p_approve boolean,
  p_review_note text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_campaign public.email_campaigns%rowtype;
  v_post public.posts%rowtype;
  v_recipient_count integer := 0;
begin
  if v_actor is null or not exists (
    select 1 from public.portal_accounts
    where user_id = v_actor and role = 'admin' and status = 'active'
  ) then
    raise exception 'Administrator access required.' using errcode = '42501';
  end if;

  select * into v_campaign from public.email_campaigns where id = p_campaign_id for update;
  if not found then raise exception 'Campaign not found.' using errcode = 'P0002'; end if;
  if v_campaign.status <> 'requested' then
    raise exception 'Only requested campaigns may be reviewed.' using errcode = '22023';
  end if;
  if p_review_note is not null and char_length(p_review_note) > 2000 then
    raise exception 'Review note is too long.' using errcode = '22023';
  end if;

  if not p_approve then
    update public.email_campaigns
    set status = 'rejected', review_note = p_review_note, updated_at = now()
    where id = p_campaign_id;
    update public.posts set mass_email_approved = false where id = v_campaign.post_id;
  else
    select * into v_post from public.posts where id = v_campaign.post_id for share;
    if v_post.status <> 'approved' then
      raise exception 'The post must be approved before its email campaign can be approved.' using errcode = '22023';
    end if;
    if v_post.scope <> v_campaign.target_scope or v_post.county_id is distinct from v_campaign.county_id then
      raise exception 'The post audience changed after the campaign was requested.' using errcode = '22023';
    end if;

    update public.email_campaigns
    set status = 'approved', approved_by = v_actor, approved_at = now(), review_note = p_review_note,
        post_snapshot = jsonb_build_object(
          'post_id', v_post.id, 'title', v_post.title, 'summary', v_post.summary,
          'body', v_post.body, 'content_type', v_post.content_type,
          'scope', v_post.scope, 'county_id', v_post.county_id,
          'cover_image_path', v_post.cover_image_path,
          'cover_image_alt', v_post.cover_image_alt,
          'updated_at', v_post.updated_at
        ), updated_at = now()
    where id = p_campaign_id;

    insert into public.email_deliveries (campaign_id, county_id, recipient_email, status)
    select distinct p_campaign_id, cc.county_id, lower(btrim(cc.email)), 'pending'
    from public.county_contacts cc
    where cc.subscription_status = 'active'
      and (v_campaign.target_scope = 'global' or cc.county_id = v_campaign.county_id)
      and not exists (
        select 1 from public.email_suppressions s where s.email = lower(btrim(cc.email))
      )
    on conflict (campaign_id, recipient_email) do nothing;

    select count(*) into v_recipient_count
    from public.email_deliveries where campaign_id = p_campaign_id;

    update public.email_campaigns
    set recipient_count = v_recipient_count,
        status = case when v_recipient_count = 0 then 'sent' else 'approved' end,
        completed_at = case when v_recipient_count = 0 then now() else completed_at end,
        updated_at = now()
    where id = p_campaign_id;
    update public.posts set mass_email_approved = true where id = v_campaign.post_id;
  end if;

  insert into public.security_audit_events (
    actor_user_id, county_id, event_type, target_table, target_id, event_data
  ) values (
    v_actor, v_campaign.county_id,
    case when p_approve then 'email_campaign_approved' else 'email_campaign_rejected' end,
    'email_campaigns', p_campaign_id::text,
    jsonb_build_object('post_id', v_campaign.post_id, 'recipient_count', v_recipient_count)
  );

  return jsonb_build_object('approved', p_approve, 'recipient_count', v_recipient_count);
end;
$$;

create or replace function public.rrg_list_email_campaigns(
  p_status text default null,
  p_page integer default 1,
  p_page_size integer default 25
)
returns table (
  id bigint, post_id bigint, post_title text, county_id bigint, county_name text,
  target_scope text, status text, subject text, requested_at timestamptz,
  approved_at timestamptz, recipient_count integer, sent_count integer,
  delivered_count integer, bounced_count integer, complained_count integer,
  failed_count integer, total_count bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_account public.portal_accounts%rowtype;
  v_page integer := greatest(coalesce(p_page, 1), 1);
  v_page_size integer := least(greatest(coalesce(p_page_size, 25), 1), 100);
begin
  if v_actor is null then raise exception 'Authentication required.' using errcode = '42501'; end if;
  select * into v_account from public.portal_accounts where user_id = v_actor;
  if not found or v_account.status <> 'active' then
    raise exception 'An active portal account is required.' using errcode = '42501';
  end if;

  return query
  select ec.id, ec.post_id, p.title, ec.county_id, c.name, ec.target_scope, ec.status,
         ec.subject, ec.requested_at, ec.approved_at, ec.recipient_count, ec.sent_count,
         ec.delivered_count, ec.bounced_count, ec.complained_count, ec.failed_count,
         count(*) over()
  from public.email_campaigns ec
  join public.posts p on p.id = ec.post_id
  left join public.counties c on c.id = ec.county_id
  where (p_status is null or ec.status = p_status)
    and (
      v_account.role = 'admin'
      or (v_account.role = 'chapter_master' and ec.county_id = v_account.county_id and ec.requested_by = v_actor)
    )
  order by ec.requested_at desc, ec.id desc
  limit v_page_size offset (v_page - 1) * v_page_size;
end;
$$;

create or replace function public.rrg_claim_email_deliveries(p_limit integer default 25)
returns table (
  delivery_id bigint, campaign_id bigint, recipient_email text, unsubscribe_token uuid,
  subject text, post_snapshot jsonb, county_name text, reply_to_email text
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.email_deliveries
  set status = 'failed', failed_at = now(), last_error_code = 'claim_timeout'
  where status = 'processing' and claimed_at < now() - interval '15 minutes' and attempt_count >= 3;

  return query
  with claimed as (
    select d.id
    from public.email_deliveries d
    join public.email_campaigns c on c.id = d.campaign_id
    where (d.status = 'pending' or (d.status = 'processing' and d.claimed_at < now() - interval '15 minutes'))
      and d.attempt_count < 3 and c.status in ('approved', 'sending')
    order by d.queued_at, d.id
    for update of d skip locked
    limit least(greatest(coalesce(p_limit, 25), 1), 100)
  ), updated as (
    update public.email_deliveries d
    set status = 'processing', claimed_at = now(), attempt_count = attempt_count + 1
    from claimed
    where d.id = claimed.id
    returning d.*
  )
  select u.id, u.campaign_id, u.recipient_email, u.unsubscribe_token,
         c.subject, c.post_snapshot, co.name,
         coalesce(nullif(btrim(co.chapter_contact_email), ''), 'rerouter@flockblocktn.org')
  from updated u
  join public.email_campaigns c on c.id = u.campaign_id
  join public.counties co on co.id = u.county_id;

  update public.email_campaigns c
  set status = 'sending', send_started_at = coalesce(send_started_at, now()), updated_at = now()
  where c.status = 'approved'
    and exists (select 1 from public.email_deliveries d where d.campaign_id = c.id and d.status = 'processing');
end;
$$;

create or replace function public.rrg_record_email_delivery_result(
  p_delivery_id bigint,
  p_sent boolean,
  p_provider_email_id text default null,
  p_error_code text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_campaign_id bigint;
begin
  update public.email_deliveries
  set status = case when p_sent then 'sent' else 'failed' end,
      provider_email_id = case when p_sent then p_provider_email_id else provider_email_id end,
      sent_at = case when p_sent then now() else sent_at end,
      failed_at = case when p_sent then failed_at else now() end,
      last_error_code = case when p_sent then null else left(coalesce(p_error_code, 'send_failed'), 80) end
  where id = p_delivery_id and status = 'processing'
  returning campaign_id into v_campaign_id;

  if v_campaign_id is null then return; end if;

  update public.email_campaigns c
  set sent_count = (select count(*) from public.email_deliveries d where d.campaign_id = c.id and d.status in ('sent','delivered')),
      failed_count = (select count(*) from public.email_deliveries d where d.campaign_id = c.id and d.status = 'failed'),
      status = case when not exists (
        select 1 from public.email_deliveries d where d.campaign_id = c.id and d.status in ('pending','processing')
      ) then case when exists (
        select 1 from public.email_deliveries d where d.campaign_id = c.id and d.status in ('sent','delivered')
      ) then 'sent' else 'failed' end else c.status end,
      completed_at = case when not exists (
        select 1 from public.email_deliveries d where d.campaign_id = c.id and d.status in ('pending','processing')
      ) then now() else c.completed_at end,
      updated_at = now()
  where c.id = v_campaign_id;
end;
$$;

create or replace function public.rrg_claim_due_reminders(p_limit integer default 25)
returns table (
  reminder_id bigint, recipient_email text, goal_title text, county_name text,
  chapter_contact_email text
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.request_followup_reminders
  set status = 'failed', failed_at = now(), last_error_code = 'claim_timeout'
  where status = 'processing' and claimed_at < now() - interval '15 minutes' and attempt_count >= 3;

  return query
  with claimed as (
    select r.id
    from public.request_followup_reminders r
    where (r.status = 'pending' or (r.status = 'processing' and r.claimed_at < now() - interval '15 minutes'))
      and r.attempt_count < 3 and r.due_at <= now()
      and not exists (select 1 from public.email_suppressions s where s.email = r.email)
    order by r.due_at, r.id
    for update of r skip locked
    limit least(greatest(coalesce(p_limit, 25), 1), 100)
  ), updated as (
    update public.request_followup_reminders r
    set status = 'processing', claimed_at = now(), attempt_count = attempt_count + 1
    from claimed
    where r.id = claimed.id
    returning r.*
  )
  select u.id, u.email, g.title, c.name,
         coalesce(nullif(btrim(c.chapter_contact_email), ''), 'rerouter@flockblocktn.org')
  from updated u
  join public.county_records_request_goals g on g.id = u.goal_id
  join public.counties c on c.id = u.county_id;

  update public.request_followup_reminders r
  set status = 'suppressed'
  where r.status = 'pending' and r.due_at <= now()
    and exists (select 1 from public.email_suppressions s where s.email = r.email);
end;
$$;

create or replace function public.rrg_record_reminder_result(
  p_reminder_id bigint,
  p_sent boolean,
  p_provider_email_id text default null,
  p_error_code text default null
)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.request_followup_reminders
  set status = case when p_sent then 'sent' else 'failed' end,
      provider_email_id = case when p_sent then p_provider_email_id else provider_email_id end,
      sent_at = case when p_sent then now() else sent_at end,
      failed_at = case when p_sent then failed_at else now() end,
      last_error_code = case when p_sent then null else left(coalesce(p_error_code, 'send_failed'), 80) end
  where id = p_reminder_id and status = 'processing';
$$;

create or replace function public.rrg_process_resend_webhook(
  p_event_id text,
  p_event_type text,
  p_provider_email_id text,
  p_recipient_email text default null
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_delivery public.email_deliveries%rowtype;
  v_email text := lower(btrim(p_recipient_email));
begin
  insert into public.email_webhook_events (event_id, event_type, provider_email_id)
  values (p_event_id, p_event_type, p_provider_email_id)
  on conflict (event_id) do nothing;
  if not found then return false; end if;

  select * into v_delivery
  from public.email_deliveries
  where provider_email_id = p_provider_email_id
  for update;

  if found then
    v_email := v_delivery.recipient_email;
    update public.email_deliveries
    set status = case
          when p_event_type = 'email.delivered' then 'delivered'
          when p_event_type = 'email.bounced' then 'bounced'
          when p_event_type = 'email.complained' then 'complained'
          else status end,
        delivered_at = case when p_event_type = 'email.delivered' then now() else delivered_at end,
        failed_at = case when p_event_type in ('email.bounced','email.complained') then now() else failed_at end
    where id = v_delivery.id;

    update public.email_campaigns c
    set delivered_count = (select count(*) from public.email_deliveries d where d.campaign_id = c.id and d.status = 'delivered'),
        bounced_count = (select count(*) from public.email_deliveries d where d.campaign_id = c.id and d.status = 'bounced'),
        complained_count = (select count(*) from public.email_deliveries d where d.campaign_id = c.id and d.status = 'complained'),
        updated_at = now()
    where c.id = v_delivery.campaign_id;
  end if;

  if p_event_type in ('email.bounced', 'email.complained') and v_email is not null then
    insert into public.email_suppressions (email, reason, source_event_id)
    values (v_email, case when p_event_type = 'email.complained' then 'complaint' else 'bounce' end, p_event_id)
    on conflict (email) do update
      set reason = excluded.reason, source_event_id = excluded.source_event_id, suppressed_at = now();
  end if;

  return true;
end;
$$;

revoke all on function public.rrg_subscribe_county_updates(bigint, text) from public;
revoke all on function public.rrg_request_followup_reminder(bigint, text) from public;
revoke all on function public.rrg_cancel_followup_reminder(uuid) from public;
revoke all on function public.rrg_unsubscribe_email(uuid) from public;
revoke all on function public.rrg_request_post_email_campaign(bigint, text) from public;
revoke all on function public.rrg_admin_review_email_campaign(bigint, boolean, text) from public;
revoke all on function public.rrg_list_email_campaigns(text, integer, integer) from public;
revoke all on function public.rrg_claim_email_deliveries(integer) from public;
revoke all on function public.rrg_record_email_delivery_result(bigint, boolean, text, text) from public;
revoke all on function public.rrg_claim_due_reminders(integer) from public;
revoke all on function public.rrg_record_reminder_result(bigint, boolean, text, text) from public;
revoke all on function public.rrg_process_resend_webhook(text, text, text, text) from public;

grant execute on function public.rrg_subscribe_county_updates(bigint, text) to anon, authenticated;
grant execute on function public.rrg_request_followup_reminder(bigint, text) to anon, authenticated;
grant execute on function public.rrg_cancel_followup_reminder(uuid) to anon, authenticated;
grant execute on function public.rrg_unsubscribe_email(uuid) to anon, authenticated;
grant execute on function public.rrg_request_post_email_campaign(bigint, text) to authenticated;
grant execute on function public.rrg_admin_review_email_campaign(bigint, boolean, text) to authenticated;
grant execute on function public.rrg_list_email_campaigns(text, integer, integer) to authenticated;

grant execute on function public.rrg_claim_email_deliveries(integer) to service_role;
grant execute on function public.rrg_record_email_delivery_result(bigint, boolean, text, text) to service_role;
grant execute on function public.rrg_claim_due_reminders(integer) to service_role;
grant execute on function public.rrg_record_reminder_result(bigint, boolean, text, text) to service_role;
grant execute on function public.rrg_process_resend_webhook(text, text, text, text) to service_role;
