-- Flock Block Tennessee
-- County records-request goal templates, public county timelines, and links
-- to hosted or external responsive records.
--
-- Target: the confirmed production schema supplied on 2026-08-14.
-- This migration adds new objects only. It does not alter request_profiles,
-- evidence_objects, or existing application content.

begin;

-- ---------------------------------------------------------------------------
-- 0. Confirm the required foundation
-- ---------------------------------------------------------------------------

do $$
begin
  if to_regclass('public.counties') is null then
    raise exception 'public.counties does not exist';
  end if;

  if to_regclass('public.portal_accounts') is null then
    raise exception 'public.portal_accounts does not exist';
  end if;

  if to_regclass('public.government_entities') is null then
    raise exception 'public.government_entities does not exist';
  end if;

  if to_regclass('public.request_profiles') is null then
    raise exception 'public.request_profiles does not exist';
  end if;

  if to_regclass('public.evidence_objects') is null then
    raise exception 'public.evidence_objects does not exist';
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 1. Permit only explicitly approved, nonpersonal PDF fill values
-- ---------------------------------------------------------------------------

create or replace function public.rrg_fill_payload_is_safe(payload jsonb)
returns boolean
language plpgsql
immutable
set search_path = ''
as $$
declare
  item jsonb;
begin
  if payload is null or jsonb_typeof(payload) <> 'object' then
    return false;
  end if;

  if (payload - array['request']) <> '{}'::jsonb then
    return false;
  end if;

  if not (payload ? 'request')
     or jsonb_typeof(payload -> 'request') <> 'object' then
    return false;
  end if;

  if (
    (payload -> 'request')
    - array[
        'records_description',
        'department_or_division',
        'record_category_label',
        'date_from_mm_dd_yyyy',
        'date_to_mm_dd_yyyy',
        'delivery_method'
      ]
  ) <> '{}'::jsonb then
    return false;
  end if;

  for item in
    select value
    from jsonb_each(payload -> 'request')
  loop
    if jsonb_typeof(item) not in ('string', 'null') then
      return false;
    end if;
  end loop;

  return true;
end;
$$;

comment on function public.rrg_fill_payload_is_safe(jsonb) is
  'Rejects personal or unrecognized fields from public request-goal fill data.';

-- ---------------------------------------------------------------------------
-- 2. Reusable goal templates, county instances, and published links
-- ---------------------------------------------------------------------------

create table if not exists public.records_request_goal_templates (
  id bigint generated by default as identity primary key,
  seed_key text not null unique,
  title text not null,
  public_summary text not null default '',
  default_fill_payload jsonb not null default '{"request": {}}'::jsonb,
  default_position integer not null default 0,
  source_county_id bigint,
  active boolean not null default true,
  created_by uuid not null default auth.uid(),
  updated_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint records_request_goal_templates_seed_key_check
    check (seed_key ~ '^[a-z0-9]+(_[a-z0-9]+)*$'),
  constraint records_request_goal_templates_title_check
    check (char_length(trim(title)) between 1 and 200),
  constraint records_request_goal_templates_summary_check
    check (char_length(public_summary) <= 2000),
  constraint records_request_goal_templates_fill_payload_check
    check (public.rrg_fill_payload_is_safe(default_fill_payload)),
  constraint records_request_goal_templates_position_check
    check (default_position >= 0),
  constraint records_request_goal_templates_source_county_fkey
    foreign key (source_county_id)
    references public.counties(id)
    on update cascade
    on delete set null,
  constraint records_request_goal_templates_created_by_fkey
    foreign key (created_by)
    references public.portal_accounts(user_id)
    on delete restrict,
  constraint records_request_goal_templates_updated_by_fkey
    foreign key (updated_by)
    references public.portal_accounts(user_id)
    on delete set null
);

create table if not exists public.county_records_request_goals (
  id bigint generated by default as identity primary key,
  county_id bigint not null,
  goal_template_id bigint,
  government_entity_id bigint,
  request_profile_id uuid,
  title text not null,
  public_summary text not null default '',
  fill_payload jsonb not null default '{"request": {}}'::jsonb,
  status text not null default 'draft',
  position integer not null default 0,
  is_public boolean not null default false,
  created_by uuid not null default auth.uid(),
  updated_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint county_records_request_goals_county_fkey
    foreign key (county_id)
    references public.counties(id)
    on update cascade
    on delete cascade,
  constraint county_records_request_goals_template_fkey
    foreign key (goal_template_id)
    references public.records_request_goal_templates(id)
    on update cascade
    on delete set null,
  constraint county_records_request_goals_entity_fkey
    foreign key (government_entity_id)
    references public.government_entities(id)
    on update cascade
    on delete restrict,
  constraint county_records_request_goals_profile_fkey
    foreign key (request_profile_id)
    references public.request_profiles(id)
    on update cascade
    on delete restrict,
  constraint county_records_request_goals_created_by_fkey
    foreign key (created_by)
    references public.portal_accounts(user_id)
    on delete restrict,
  constraint county_records_request_goals_updated_by_fkey
    foreign key (updated_by)
    references public.portal_accounts(user_id)
    on delete set null,
  constraint county_records_request_goals_title_check
    check (char_length(trim(title)) between 1 and 200),
  constraint county_records_request_goals_summary_check
    check (char_length(public_summary) <= 2000),
  constraint county_records_request_goals_fill_payload_check
    check (public.rrg_fill_payload_is_safe(fill_payload)),
  constraint county_records_request_goals_status_check
    check (
      status in (
        'draft',
        'profile_needed',
        'ready',
        'requested',
        'received',
        'published',
        'unavailable',
        'retired'
      )
    ),
  constraint county_records_request_goals_position_check
    check (position >= 0),
  constraint county_records_request_goals_public_state_check
    check (not is_public or status not in ('draft', 'retired'))
);

create table if not exists public.records_request_goal_links (
  id bigint generated by default as identity primary key,
  goal_id bigint not null,
  label text not null,
  evidence_object_id uuid,
  external_url text,
  position integer not null default 0,
  is_primary boolean not null default false,
  created_by uuid not null default auth.uid(),
  updated_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint records_request_goal_links_goal_fkey
    foreign key (goal_id)
    references public.county_records_request_goals(id)
    on update cascade
    on delete cascade,
  constraint records_request_goal_links_evidence_fkey
    foreign key (evidence_object_id)
    references public.evidence_objects(id)
    on update cascade
    on delete restrict,
  constraint records_request_goal_links_created_by_fkey
    foreign key (created_by)
    references public.portal_accounts(user_id)
    on delete restrict,
  constraint records_request_goal_links_updated_by_fkey
    foreign key (updated_by)
    references public.portal_accounts(user_id)
    on delete set null,
  constraint records_request_goal_links_label_check
    check (char_length(trim(label)) between 1 and 200),
  constraint records_request_goal_links_destination_check
    check (num_nonnulls(evidence_object_id, external_url) = 1),
  constraint records_request_goal_links_external_url_check
    check (external_url is null or external_url ~* '^https://'),
  constraint records_request_goal_links_position_check
    check (position >= 0)
);

create unique index if not exists county_records_request_goals_template_once_idx
  on public.county_records_request_goals(county_id, goal_template_id)
  where goal_template_id is not null;

create index if not exists county_records_request_goals_public_timeline_idx
  on public.county_records_request_goals(county_id, position, id)
  where is_public and status not in ('draft', 'retired');

create index if not exists county_records_request_goals_profile_idx
  on public.county_records_request_goals(request_profile_id)
  where request_profile_id is not null;

create index if not exists records_request_goal_links_goal_position_idx
  on public.records_request_goal_links(goal_id, position, id);

create unique index if not exists records_request_goal_links_one_primary_idx
  on public.records_request_goal_links(goal_id)
  where is_primary;

-- ---------------------------------------------------------------------------
-- 3. Keep cross-table county and profile relationships consistent
-- ---------------------------------------------------------------------------

create or replace function public.rrg_validate_goal_relationships()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  entity_county_id bigint;
  profile_entity_id bigint;
begin
  if new.government_entity_id is not null then
    select entity.county_id
    into entity_county_id
    from public.government_entities as entity
    where entity.id = new.government_entity_id;

    if entity_county_id is not null and entity_county_id <> new.county_id then
      raise exception 'The government entity does not belong to this county';
    end if;
  end if;

  if new.request_profile_id is not null then
    if new.government_entity_id is null then
      raise exception 'A request profile requires a government entity';
    end if;

    select profile.government_entity_id
    into profile_entity_id
    from public.request_profiles as profile
    where profile.id = new.request_profile_id;

    if profile_entity_id is distinct from new.government_entity_id then
      raise exception 'The request profile belongs to a different government entity';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists rrg_validate_goal_relationships
  on public.county_records_request_goals;
create trigger rrg_validate_goal_relationships
before insert or update of county_id, government_entity_id, request_profile_id
on public.county_records_request_goals
for each row execute function public.rrg_validate_goal_relationships();

create or replace function public.rrg_validate_link_relationships()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  goal_county_id bigint;
  evidence_county_id bigint;
begin
  if new.evidence_object_id is null then
    return new;
  end if;

  select goal.county_id
  into goal_county_id
  from public.county_records_request_goals as goal
  where goal.id = new.goal_id;

  select evidence.county_id
  into evidence_county_id
  from public.evidence_objects as evidence
  where evidence.id = new.evidence_object_id;

  if evidence_county_id is not null
     and evidence_county_id <> goal_county_id then
    raise exception 'The hosted document belongs to a different county';
  end if;

  return new;
end;
$$;

drop trigger if exists rrg_validate_link_relationships
  on public.records_request_goal_links;
create trigger rrg_validate_link_relationships
before insert or update of goal_id, evidence_object_id
on public.records_request_goal_links
for each row execute function public.rrg_validate_link_relationships();

create or replace function public.rrg_touch_template()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.created_by := old.created_by;
  new.created_at := old.created_at;
  new.updated_at := now();
  if auth.uid() is not null then
    new.updated_by := auth.uid();
  end if;
  return new;
end;
$$;

create or replace function public.rrg_touch_goal()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.created_by := old.created_by;
  new.created_at := old.created_at;
  new.updated_at := now();
  if auth.uid() is not null then
    new.updated_by := auth.uid();
  end if;
  return new;
end;
$$;

create or replace function public.rrg_touch_link()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.created_by := old.created_by;
  new.created_at := old.created_at;
  new.updated_at := now();
  if auth.uid() is not null then
    new.updated_by := auth.uid();
  end if;
  return new;
end;
$$;

drop trigger if exists rrg_touch_template
  on public.records_request_goal_templates;
create trigger rrg_touch_template
before update on public.records_request_goal_templates
for each row execute function public.rrg_touch_template();

drop trigger if exists rrg_touch_goal
  on public.county_records_request_goals;
create trigger rrg_touch_goal
before update on public.county_records_request_goals
for each row execute function public.rrg_touch_goal();

drop trigger if exists rrg_touch_link
  on public.records_request_goal_links;
create trigger rrg_touch_link
before update on public.records_request_goal_links
for each row execute function public.rrg_touch_link();

-- ---------------------------------------------------------------------------
-- 4. Permission helpers
-- ---------------------------------------------------------------------------

create or replace function public.rrg_is_active_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (
      select account.role = 'admin' and account.status = 'active'
      from public.portal_accounts as account
      where account.user_id = auth.uid()
    ),
    false
  );
$$;

create or replace function public.rrg_can_manage_county(requested_county_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (
      select
        account.status = 'active'
        and (
          account.role = 'admin'
          or (
            account.role = 'chapter_master'
            and account.county_id = requested_county_id
          )
        )
      from public.portal_accounts as account
      where account.user_id = auth.uid()
    ),
    false
  );
$$;

create or replace function public.rrg_can_manage_goal(requested_goal_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (
      select public.rrg_can_manage_county(goal.county_id)
      from public.county_records_request_goals as goal
      where goal.id = requested_goal_id
    ),
    false
  );
$$;

create or replace function public.rrg_goal_is_public(requested_goal_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.county_records_request_goals as goal
    where goal.id = requested_goal_id
      and goal.is_public
      and goal.status not in ('draft', 'retired')
  );
$$;

create or replace function public.rrg_evidence_is_public(requested_evidence_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select requested_evidence_id is not null
    and exists (
      select 1
      from public.evidence_objects as evidence
      where evidence.id = requested_evidence_id
        and evidence.status = 'published'
        and evidence.visibility = 'public'
    );
$$;

revoke all on function public.rrg_is_active_admin() from public;
revoke all on function public.rrg_can_manage_county(bigint) from public;
revoke all on function public.rrg_can_manage_goal(bigint) from public;
revoke all on function public.rrg_goal_is_public(bigint) from public;
revoke all on function public.rrg_evidence_is_public(uuid) from public;

grant execute on function public.rrg_is_active_admin() to authenticated;
grant execute on function public.rrg_can_manage_county(bigint) to authenticated;
grant execute on function public.rrg_can_manage_goal(bigint) to authenticated;
grant execute on function public.rrg_goal_is_public(bigint) to anon, authenticated;
grant execute on function public.rrg_evidence_is_public(uuid) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 5. Grants and row-level security
-- ---------------------------------------------------------------------------

grant select on public.records_request_goal_templates to authenticated;
grant insert, update, delete on public.records_request_goal_templates to authenticated;

grant select on public.county_records_request_goals to anon, authenticated;
grant insert, update, delete on public.county_records_request_goals to authenticated;

grant select on public.records_request_goal_links to anon, authenticated;
grant insert, update, delete on public.records_request_goal_links to authenticated;

do $$
declare
  table_name text;
  sequence_name text;
begin
  foreach table_name in array array[
    'records_request_goal_templates',
    'county_records_request_goals',
    'records_request_goal_links'
  ]
  loop
    sequence_name := pg_get_serial_sequence('public.' || table_name, 'id');
    if sequence_name is null then
      raise exception 'public.%.id has no attached identity sequence', table_name;
    end if;
    execute format(
      'grant usage, select on sequence %s to authenticated',
      sequence_name::regclass
    );
  end loop;
end
$$;

alter table public.records_request_goal_templates enable row level security;
alter table public.county_records_request_goals enable row level security;
alter table public.records_request_goal_links enable row level security;

drop policy if exists "Operators can read active goal templates"
  on public.records_request_goal_templates;
create policy "Operators can read active goal templates"
on public.records_request_goal_templates
for select
to authenticated
using (active or public.rrg_is_active_admin());

drop policy if exists "Admins can insert goal templates"
  on public.records_request_goal_templates;
create policy "Admins can insert goal templates"
on public.records_request_goal_templates
for insert
to authenticated
with check (
  created_by = auth.uid()
  and public.rrg_is_active_admin()
);

drop policy if exists "Admins can update goal templates"
  on public.records_request_goal_templates;
create policy "Admins can update goal templates"
on public.records_request_goal_templates
for update
to authenticated
using (public.rrg_is_active_admin())
with check (public.rrg_is_active_admin());

drop policy if exists "Admins can delete goal templates"
  on public.records_request_goal_templates;
create policy "Admins can delete goal templates"
on public.records_request_goal_templates
for delete
to authenticated
using (public.rrg_is_active_admin());

drop policy if exists "Public can read visible county goals"
  on public.county_records_request_goals;
create policy "Public can read visible county goals"
on public.county_records_request_goals
for select
to anon, authenticated
using (is_public and status not in ('draft', 'retired'));

drop policy if exists "Operators can read managed county goals"
  on public.county_records_request_goals;
create policy "Operators can read managed county goals"
on public.county_records_request_goals
for select
to authenticated
using (public.rrg_can_manage_county(county_id));

drop policy if exists "Operators can insert managed county goals"
  on public.county_records_request_goals;
create policy "Operators can insert managed county goals"
on public.county_records_request_goals
for insert
to authenticated
with check (
  created_by = auth.uid()
  and public.rrg_can_manage_county(county_id)
);

drop policy if exists "Operators can update managed county goals"
  on public.county_records_request_goals;
create policy "Operators can update managed county goals"
on public.county_records_request_goals
for update
to authenticated
using (public.rrg_can_manage_county(county_id))
with check (public.rrg_can_manage_county(county_id));

drop policy if exists "Operators can delete managed county goals"
  on public.county_records_request_goals;
create policy "Operators can delete managed county goals"
on public.county_records_request_goals
for delete
to authenticated
using (public.rrg_can_manage_county(county_id));

drop policy if exists "Public can read published goal links"
  on public.records_request_goal_links;
create policy "Public can read published goal links"
on public.records_request_goal_links
for select
to anon, authenticated
using (
  public.rrg_goal_is_public(goal_id)
  and (
    external_url is not null
    or public.rrg_evidence_is_public(evidence_object_id)
  )
);

drop policy if exists "Operators can read managed goal links"
  on public.records_request_goal_links;
create policy "Operators can read managed goal links"
on public.records_request_goal_links
for select
to authenticated
using (public.rrg_can_manage_goal(goal_id));

drop policy if exists "Operators can insert managed goal links"
  on public.records_request_goal_links;
create policy "Operators can insert managed goal links"
on public.records_request_goal_links
for insert
to authenticated
with check (
  created_by = auth.uid()
  and public.rrg_can_manage_goal(goal_id)
);

drop policy if exists "Operators can update managed goal links"
  on public.records_request_goal_links;
create policy "Operators can update managed goal links"
on public.records_request_goal_links
for update
to authenticated
using (public.rrg_can_manage_goal(goal_id))
with check (public.rrg_can_manage_goal(goal_id));

drop policy if exists "Operators can delete managed goal links"
  on public.records_request_goal_links;
create policy "Operators can delete managed goal links"
on public.records_request_goal_links
for delete
to authenticated
using (public.rrg_can_manage_goal(goal_id));

-- Trigger functions are not intended to be called directly.
revoke all on function public.rrg_validate_goal_relationships() from public;
revoke all on function public.rrg_validate_link_relationships() from public;
revoke all on function public.rrg_touch_template() from public;
revoke all on function public.rrg_touch_goal() from public;
revoke all on function public.rrg_touch_link() from public;

-- ---------------------------------------------------------------------------
-- 6. Idempotently clone active templates into a county
-- ---------------------------------------------------------------------------

create or replace function public.clone_records_request_goal_templates(
  target_county_id bigint,
  template_seed_keys text[] default null
)
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
  inserted_count integer;
begin
  if not public.rrg_can_manage_county(target_county_id) then
    raise exception 'You cannot manage this county';
  end if;

  insert into public.county_records_request_goals (
    county_id,
    goal_template_id,
    title,
    public_summary,
    fill_payload,
    status,
    position,
    is_public,
    created_by,
    updated_by
  )
  select
    target_county_id,
    template.id,
    template.title,
    template.public_summary,
    template.default_fill_payload,
    'profile_needed',
    template.default_position,
    false,
    auth.uid(),
    auth.uid()
  from public.records_request_goal_templates as template
  where template.active
    and (
      template_seed_keys is null
      or template.seed_key = any(template_seed_keys)
    )
  on conflict (county_id, goal_template_id)
    where goal_template_id is not null
  do nothing;

  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;

revoke all on function public.clone_records_request_goal_templates(bigint, text[])
  from public;
grant execute on function public.clone_records_request_goal_templates(bigint, text[])
  to authenticated;

commit;

-- ---------------------------------------------------------------------------
-- 7. One-result Supabase verification
-- ---------------------------------------------------------------------------

select jsonb_build_object(
  'goal_templates_table',
    to_regclass('public.records_request_goal_templates') is not null,
  'county_goals_table',
    to_regclass('public.county_records_request_goals') is not null,
  'goal_links_table',
    to_regclass('public.records_request_goal_links') is not null,
  'goal_template_count',
    (select count(*) from public.records_request_goal_templates),
  'county_goal_count',
    (select count(*) from public.county_records_request_goals),
  'goal_link_count',
    (select count(*) from public.records_request_goal_links),
  'row_level_security',
    (
      select jsonb_object_agg(table_name, rowsecurity)
      from (
        select relname as table_name, relrowsecurity as rowsecurity
        from pg_class
        where oid in (
          'public.records_request_goal_templates'::regclass,
          'public.county_records_request_goals'::regclass,
          'public.records_request_goal_links'::regclass
        )
      ) as rls_state
    )
) as records_request_goals_migration;
